import './globals.css';

import { type Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';

import { ThemeProvider } from '@/components/ThemeProvider.tsx';
import { NavTabLink, NavTabs } from '@/components/ui/NavTabs.tsx';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="absolute inset-[0] flex flex-col">
            <header className="container flex items-center justify-center w-full bg-color border-b border-zinc-700 py-2">
              <NavTabs>
                <NavTabLink className="text-xl px-4 py-2" href="/">
                  Lights
                </NavTabLink>
                <NavTabLink className="text-xl px-4 py-2" href="/colors">
                  Colors
                </NavTabLink>
                <NavTabLink className="text-xl px-4 py-2" href="/cleaning">
                  Cleaning
                </NavTabLink>
              </NavTabs>
            </header>
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
