import { IState, ITemperatureEntry, ICleaningEntry, ITestingEntry, IConfig } from './common/common';
export declare function init(): Promise<void>;
export declare function getState(): Promise<IState | undefined>;
export declare function updateState(newState: IState): Promise<void>;
export declare function getConfig(): Promise<IConfig | undefined>;
export declare function updateConfig(config: IConfig): Promise<void>;
export declare function getTemperatureHistory(): Promise<ITemperatureEntry[]>;
export declare function getCleaningHistory(): Promise<ICleaningEntry[]>;
export declare function createCleaningEntry(cleaningEntry: ICleaningEntry): Promise<void>;
export declare function getTestingHistory(): Promise<ITestingEntry[]>;
export declare function createTestingEntry(cleaningEntry: ITestingEntry): Promise<void>;
